CREATE TABLE `service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) DEFAULT NULL, 
  `subtitle` VARCHAR(255) DEFAULT NULL, 
  `phone` VARCHAR(255) DEFAULT NULL, 
  `address` VARCHAR(255) DEFAULT NULL, 
  `other_phone` VARCHAR(255) DEFAULT NULL, 
  `email` VARCHAR(255) DEFAULT NULL, 
  `url` VARCHAR(255) DEFAULT NULL, 
  `week_days` VARCHAR(255) DEFAULT NULL, 
  `start_time` VARCHAR(255) DEFAULT NULL, 
  `end_time` VARCHAR(255) DEFAULT NULL, 
  `visits` INT DEFAULT NULL, 
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`)
);
